<a href="https://colab.research.google.com/github/omerceyhann/omerceyhann/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
one_dimensional_array = np.array([1.5, 2.5, 3.5, 5.3, 6.7, 7.9, 8.5,9.9])
print(one_dimensional_array)


[1.5 2.5 3.5 5.3 6.7 7.9 8.5 9.9]


In [ ]:
sort_of_integers = np.arange(3, 8)
print(sort_of_integers)

[3 4 5 6 7]


In [ ]:
two_dimensional_array = np.array([[4, 4], [5, 3], [2, 5]])
print(two_dimensional_array)

[[4 4]
 [5 3]
 [2 5]]


In [ ]:
random_integers_between_10_and_50 = np.random.randint(low=10, high=50, size=(6))
print(random_integers_between_10_and_50)

[45 49 16 29 24 16]


In [ ]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.04493683 0.38749618 0.13577257 0.05221077 0.11954324 0.18054242]


In [ ]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)


[ 0.48545099 -1.83565546 -0.23235284 -0.89000891 -0.64964092  0.80379603
 -1.51388384  0.4569546   1.67399897  1.56419845 -0.62070203 -0.30370968
 -1.63696757 -1.81488309  0.99338946]
[22.48545099 23.16434454 27.76764716 30.10999109 33.35035908 37.80379603
 38.48611616 43.4569546  47.67399897 50.56419845 51.37929797 54.69629032
 56.36303243 59.18511691 64.99338946]


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [ ]:
# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Print the entire DataFrame
print(my_dataframe)

In [ ]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

In [ ]:

my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

my_data = np.random.randint(low=0, high=101, size=(3, 4))

df = pd.DataFrame(data=my_data, columns=my_column_names)

print(df)

print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])


df['Janet'] = df['Tahani'] + df['Jason']

print(df)

   Eleanor  Chidi  Tahani  Jason
0       64     12      95     84
1       76     46      58     64
2       29     13      40     86

Second row of the Eleanor column: 76

   Eleanor  Chidi  Tahani  Jason  Janet
0       64     12      95     84    179
1       76     46      58     64    122
2       29     13      40     86    126
